/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.vista;

import java.awt.Color;
import javax.swing.JOptionPane;
import ucr.ac.cr.controlador.ControladorInicio;

/**
 *
 * @author Mónica Artavia
 */
public class GUIInicio extends javax.swing.JFrame {
    
    private ControladorInicio controlador;
    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
        controlador = new ControladorInicio(this, panelMenu, panelSplashscreen, panelRegistro);
        panelSplashscreen.escuchar(controlador);
        panelMenu.escuchar(controlador);
        panelMenu.ocultarCancelar();
        panelMenu.mostrarRegistro();
        panelRegistro.escuchar(controlador);
        panelRegistro.ocultarCancelado();
        this.escuchar(controlador);
        controlador.reproducirMusica();
        mostrarSplash();
        mostrarCreditos(false);
        mostrarVersion(false);
        mostrarComentarios(false);
        botonCerrarMB(false);
        this.instru1(false);
        this.instru2(false);
        this.instru3(false);
        this.botonCerrar(false);
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public ControladorInicio getControlador() {
        return controlador;
    }

    public PanelMenu getPanelMenu() {
        return panelMenu;
    }

    public void mostrarMensaje(String mensaje, String mensaje2){
        JOptionPane.showMessageDialog(null, mensaje +""+ mensaje2);
    }
    
    public void mostrarSplash(){
        panelSplashscreen.setVisible(true);
        panelMenu.setVisible(false);
        panelRegistro.setVisible(false);
        jMenuBar1.setVisible(false);
    }
    
    public void mostrarMenu(){
        panelSplashscreen.setVisible(false);
        panelMenu.setVisible(true);
        panelRegistro.setVisible(false);
        jMenuBar1.setVisible(true);
    }
    
    public void mostrarRegistro(){
        panelSplashscreen.setVisible(false);
        panelMenu.setVisible(false);
        panelRegistro.setVisible(true);
        jMenuBar1.setVisible(false);
    }
    
    public void mostrarCreditos(boolean estado){
        lblCreditos.setVisible(estado);
    }
    
    public void mostrarComentarios(boolean estado){
        lblComentarios.setVisible(estado);
    }
    
    public void mostrarVersion(boolean estado){
        lblVersion.setVisible(estado);
    }
    
    public void botonCerrarMB(boolean estado){
        btnCerrarMB.setVisible(estado);
    }
    
    public void instru1(boolean estado){
        lblIns1.setVisible(estado);
        btnDerecha1.setVisible(estado);
    }
    
    public void instru2(boolean estado){
        lblIns2.setVisible(estado);
        btnDerecha2.setVisible(estado);
        btnIzquierda1.setVisible(estado);
    }
    
    public void instru3(boolean estado){
        lblIns3.setVisible(estado);
        btnIzquierda2.setVisible(estado);
    }
    
    public void botonCerrar(boolean estado){
        btnCerrarIns.setVisible(estado);
    }
    
    public void escuchar(ControladorInicio controlador){
        btnDerecha1.addActionListener(controlador);
        btnDerecha2.addActionListener(controlador);
        btnIzquierda1.addActionListener(controlador);
        btnIzquierda2.addActionListener(controlador);
        btnCerrarIns.addActionListener(controlador);
        btnCerrarMB.addActionListener(controlador);
        jiCreditos.addActionListener(controlador);
        jiVersion.addActionListener(controlador);
        jiComentarios.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCerrarMB = new javax.swing.JButton();
        lblVersion = new javax.swing.JLabel();
        lblComentarios = new javax.swing.JLabel();
        lblCreditos = new javax.swing.JLabel();
        btnCerrarIns = new javax.swing.JButton();
        btnDerecha2 = new javax.swing.JButton();
        btnIzquierda2 = new javax.swing.JButton();
        lblIns3 = new javax.swing.JLabel();
        btnIzquierda1 = new javax.swing.JButton();
        lblIns2 = new javax.swing.JLabel();
        btnDerecha1 = new javax.swing.JButton();
        lblIns1 = new javax.swing.JLabel();
        panelRegistro = new ucr.ac.cr.vista.PanelRegistro();
        panelMenu = new ucr.ac.cr.vista.PanelMenu();
        panelSplashscreen = new ucr.ac.cr.vista.PanelSplashscreen();
        jMenuBar1 = new javax.swing.JMenuBar();
        jInformacion = new javax.swing.JMenu();
        jiVersion = new javax.swing.JMenuItem();
        jiComentarios = new javax.swing.JMenuItem();
        jiCreditos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrarMB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CERRAR.png"))); // NOI18N
        btnCerrarMB.setActionCommand("Cerrar MB");
        btnCerrarMB.setBorderPainted(false);
        btnCerrarMB.setContentAreaFilled(false);
        btnCerrarMB.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CERRAR.png"))); // NOI18N
        btnCerrarMB.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CRR.png"))); // NOI18N
        getContentPane().add(btnCerrarMB, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 670, -1, -1));

        lblVersion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VERSION.png"))); // NOI18N
        getContentPane().add(lblVersion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 720, 1080));

        lblComentarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/COMENTARIOS.png"))); // NOI18N
        getContentPane().add(lblComentarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 720, 1080));

        lblCreditos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CREDITOS.png"))); // NOI18N
        getContentPane().add(lblCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 720, 1080));

        btnCerrarIns.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CERRAR.png"))); // NOI18N
        btnCerrarIns.setActionCommand("Cerrar Ins");
        btnCerrarIns.setBorderPainted(false);
        btnCerrarIns.setContentAreaFilled(false);
        btnCerrarIns.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CERRAR.png"))); // NOI18N
        btnCerrarIns.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CRR.png"))); // NOI18N
        getContentPane().add(btnCerrarIns, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 710, -1, -1));

        btnDerecha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DERECHA.png"))); // NOI18N
        btnDerecha2.setActionCommand("Derecha 2");
        btnDerecha2.setBorderPainted(false);
        btnDerecha2.setContentAreaFilled(false);
        btnDerecha2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DERECHA.png"))); // NOI18N
        btnDerecha2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DR.png"))); // NOI18N
        getContentPane().add(btnDerecha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 710, -1, -1));

        btnIzquierda2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IZQUIERDA.png"))); // NOI18N
        btnIzquierda2.setActionCommand("Izquierda 2");
        btnIzquierda2.setBorderPainted(false);
        btnIzquierda2.setContentAreaFilled(false);
        btnIzquierda2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IZQUIERDA.png"))); // NOI18N
        btnIzquierda2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IZ.png"))); // NOI18N
        getContentPane().add(btnIzquierda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, -1, -1));

        lblIns3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIns3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INSTRUCCIONES 3.png"))); // NOI18N
        getContentPane().add(lblIns3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 720, 1080));

        btnIzquierda1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IZQUIERDA.png"))); // NOI18N
        btnIzquierda1.setActionCommand("Izquierda 1");
        btnIzquierda1.setBorderPainted(false);
        btnIzquierda1.setContentAreaFilled(false);
        btnIzquierda1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IZQUIERDA.png"))); // NOI18N
        btnIzquierda1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IZ.png"))); // NOI18N
        getContentPane().add(btnIzquierda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 710, -1, -1));

        lblIns2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIns2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INSTRUCCIONES 2.png"))); // NOI18N
        getContentPane().add(lblIns2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 720, 1080));

        btnDerecha1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DERECHA.png"))); // NOI18N
        btnDerecha1.setActionCommand("Derecha 1");
        btnDerecha1.setBorderPainted(false);
        btnDerecha1.setContentAreaFilled(false);
        btnDerecha1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DERECHA.png"))); // NOI18N
        btnDerecha1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/DR.png"))); // NOI18N
        getContentPane().add(btnDerecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 710, -1, -1));

        lblIns1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIns1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INSTRUCCIONES 1.png"))); // NOI18N
        getContentPane().add(lblIns1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 720, 1080));
        getContentPane().add(panelRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        getContentPane().add(panelSplashscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenuBar1.setBackground(new java.awt.Color(153, 204, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setOpaque(false);

        jInformacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INFORMACION.png"))); // NOI18N
        jInformacion.setActionCommand("Informacion");
        jInformacion.setContentAreaFilled(false);
        jInformacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INFORMACION.png"))); // NOI18N
        jInformacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IMB.png"))); // NOI18N

        jiVersion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VERSION BTN.png"))); // NOI18N
        jiVersion.setActionCommand("Version");
        jiVersion.setContentAreaFilled(false);
        jiVersion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VERSION BTN.png"))); // NOI18N
        jiVersion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VSB.png"))); // NOI18N
        jInformacion.add(jiVersion);

        jiComentarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/COMENTARIOS BTN.png"))); // NOI18N
        jiComentarios.setActionCommand("Comentarios");
        jiComentarios.setContentAreaFilled(false);
        jiComentarios.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/COMENTARIOS BTN.png"))); // NOI18N
        jiComentarios.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CMB.png"))); // NOI18N
        jInformacion.add(jiComentarios);

        jiCreditos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CREDITOS BTN.png"))); // NOI18N
        jiCreditos.setActionCommand("Creditos");
        jInformacion.add(jiCreditos);

        jMenuBar1.add(jInformacion);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIInicio().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarIns;
    private javax.swing.JButton btnCerrarMB;
    private javax.swing.JButton btnDerecha1;
    private javax.swing.JButton btnDerecha2;
    private javax.swing.JButton btnIzquierda1;
    private javax.swing.JButton btnIzquierda2;
    private javax.swing.JMenu jInformacion;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jiComentarios;
    private javax.swing.JMenuItem jiCreditos;
    private javax.swing.JMenuItem jiVersion;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblCreditos;
    private javax.swing.JLabel lblIns1;
    private javax.swing.JLabel lblIns2;
    private javax.swing.JLabel lblIns3;
    private javax.swing.JLabel lblVersion;
    private ucr.ac.cr.vista.PanelMenu panelMenu;
    private ucr.ac.cr.vista.PanelRegistro panelRegistro;
    private ucr.ac.cr.vista.PanelSplashscreen panelSplashscreen;
    // End of variables declaration//GEN-END:variables
}
