/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.vista;

import ucr.ac.cr.controlador.ControladorInicio;

/**
 *
 * @author Mónica Artavia
 */
public class PanelMenu extends javax.swing.JPanel {

    private ControladorInicio controlador;
    /**
     * Creates new form PanelMenu
     */
    public PanelMenu() {
        initComponents();
    }
    
    public void escuchar(ControladorInicio controlador){
        btnRegistro.addActionListener(controlador);
        btnJugar.addActionListener(controlador);
        btnInstrucciones.addActionListener(controlador);
        btnSalir.addActionListener(controlador);
        btnCancelar.addActionListener(controlador);
    }
    
    public void botonesParaMensajes(boolean estado){
        btnRegistro.setVisible(estado);
        btnJugar.setVisible(estado);
        btnInstrucciones.setVisible(estado);
        btnSalir.setVisible(estado);
        btnCancelar.setVisible(estado);
    }
    
    public void mostrarDosBotones(boolean estado){
        btnInstrucciones.setVisible(estado);
        btnSalir.setVisible(estado);
    }

    public void esconderRegistro(){
        btnRegistro.setVisible(false);
        btnJugar.setVisible(true);
    }
    
    public void mostrarRegistro(){
        btnRegistro.setVisible(true);
        btnJugar.setVisible(false);
    }
    
    public void mostrarCancelar(){
        btnCancelar.setVisible(true);    }
    
    public void ocultarCancelar(){
        btnCancelar.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CANCELAR.png"))); // NOI18N
        btnCancelar.setActionCommand("Cancelar Registro");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CANCELAR.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CRM.png"))); // NOI18N
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 180, 60));

        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/REGISTRARSE.png"))); // NOI18N
        btnRegistro.setActionCommand("Registrar Juego");
        btnRegistro.setBorderPainted(false);
        btnRegistro.setContentAreaFilled(false);
        btnRegistro.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/REGISTRARSE.png"))); // NOI18N
        btnRegistro.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RO.png"))); // NOI18N
        add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 180, 60));

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JUGAR.png"))); // NOI18N
        btnJugar.setToolTipText("");
        btnJugar.setActionCommand("Jugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JUGAR.png"))); // NOI18N
        btnJugar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/JM.png"))); // NOI18N
        add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 180, 60));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SALIR.png"))); // NOI18N
        btnSalir.setActionCommand("Salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SALIR.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SM.png"))); // NOI18N
        add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 590, 180, 60));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INSTRUCCIONES.png"))); // NOI18N
        btnInstrucciones.setActionCommand("Instrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        btnInstrucciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/INSTRUCCIONES.png"))); // NOI18N
        btnInstrucciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/IM.png"))); // NOI18N
        add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 530, 180, 60));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel fondo;
    // End of variables declaration//GEN-END:variables
}
