/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.vista;

import ucr.ac.cr.controlador.ControladorInicio;

/**
 *
 * @author Mónica Artavia
 */
public class PanelSplashscreen extends javax.swing.JPanel {

    private ControladorInicio controlador;
    /**
     * Creates new form PanelSplashscreen
     */
    public PanelSplashscreen() {
        initComponents();
    }
    
    public void escuchar(ControladorInicio controlador){
        btnPlay.addActionListener(controlador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fondoS = new javax.swing.JLabel();
        btnPlay = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESIONE AQUI PARA INICIAR");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 850, -1, 90));

        fondoS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inicio.png"))); // NOI18N
        add(fondoS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnPlay.setText("Play");
        add(btnPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 793, 360, 210));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlay;
    private javax.swing.JLabel fondoS;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
