/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.vista;

import ucr.ac.cr.controlador.ControladorA;
import ucr.ac.cr.controlador.ControladorG;

/**
 *
 * @author Mónica Artavia
 */
public class PanelCompra extends javax.swing.JPanel {

    private ControladorA controlador;
    private ControladorG controladorG;
    /**
     * Creates new form PanelCompra
     */
    public PanelCompra() {
        initComponents();
    }
    
    public void escucharA(ControladorA controlador){
        btnCAgua.addActionListener(controlador);
        btnCCarne.addActionListener(controlador);
        btnCCerdo.addActionListener(controlador);
        btnCLeche.addActionListener(controlador);
        btnCPescado.addActionListener(controlador);
        btnCPollo.addActionListener(controlador);
        btnMedicina.addActionListener(controlador);
        btnPastilla.addActionListener(controlador);
        btnJabon.addActionListener(controlador);
        btnVolver.addActionListener(controlador);
    }
    
    public void escucharG(ControladorG controladorG){
        btnCAgua.addActionListener(controladorG);
        btnCCarne.addActionListener(controladorG);
        btnCCerdo.addActionListener(controladorG);
        btnCLeche.addActionListener(controladorG);
        btnCPescado.addActionListener(controladorG);
        btnCPollo.addActionListener(controladorG);
        btnMedicina.addActionListener(controladorG);
        btnPastilla.addActionListener(controladorG);
        btnJabon.addActionListener(controladorG);
        btnVolver.addActionListener(controladorG);
    }
    
    public void deshabilitarResultado(boolean estado){
        btnCAgua.setVisible(estado);
        btnCCarne.setVisible(estado);
        btnCCerdo.setVisible(estado);
        btnCLeche.setVisible(estado);
        btnCPescado.setVisible(estado);
        btnCPollo.setVisible(estado);
        btnMedicina.setVisible(estado);
        btnPastilla.setVisible(estado);
        btnJabon.setVisible(estado);
        btnVolver.setVisible(estado);
    }
    
    public void mostrarLeche(String titulo){
        leche.setText(titulo);
    }
    
    public void mostrarAgua(String titulo){
        agua.setText(titulo);
    }
    
    public void mostrarCerdo(String titulo){
        cerdo.setText(titulo);
    }
    
    public void mostrarCarne(String titulo){
        carne.setText(titulo);
    }
    
    public void mostrarPescado(String titulo){
        pescado.setText(titulo);
    }
    
    public void mostrarPollo(String titulo){
        pollo.setText(titulo);
    }
    
    public void mostrarPastilla(String titulo){
        pastilla.setText(titulo);
    }
    
    public void mostrarMedicina(String titulo){
        medicina.setText(titulo);
    }
    
    public void mostrarDinero(String titulo){
        dinero.setText(titulo);
    }
    
    public void mostrarJabon(String titulo){
        jabon.setText(titulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jabon = new javax.swing.JLabel();
        btnJabon = new javax.swing.JButton();
        pastilla = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        medicina = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnMedicina = new javax.swing.JButton();
        btnPastilla = new javax.swing.JButton();
        leche = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        agua = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pollo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pescado = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        carne = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCLeche = new javax.swing.JButton();
        btnCPollo = new javax.swing.JButton();
        btnCPescado = new javax.swing.JButton();
        btnCAgua = new javax.swing.JButton();
        btnCCarne = new javax.swing.JButton();
        btnCCerdo = new javax.swing.JButton();
        cerdo = new javax.swing.JLabel();
        dinero = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel9.setText("Pastilla:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 860, -1, -1));

        jabon.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        jabon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(jabon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 850, 60, 30));

        btnJabon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jabon 2.png"))); // NOI18N
        btnJabon.setActionCommand("Comprar Jabon");
        btnJabon.setBorderPainted(false);
        btnJabon.setContentAreaFilled(false);
        btnJabon.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jabon 2.png"))); // NOI18N
        btnJabon.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jabon 3.png"))); // NOI18N
        add(btnJabon, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 730, 110, 110));

        pastilla.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pastilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(pastilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 850, 60, 30));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel10.setText("Jabon:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 860, -1, -1));

        medicina.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        medicina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(medicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 850, 60, 30));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VOLVER A.png"))); // NOI18N
        btnVolver.setActionCommand("Volver Pantalla");
        btnVolver.setBorderPainted(false);
        btnVolver.setContentAreaFilled(false);
        btnVolver.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VOLVER A.png"))); // NOI18N
        btnVolver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/VAP.png"))); // NOI18N
        add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 910, 70, 70));

        btnMedicina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicina.png"))); // NOI18N
        btnMedicina.setActionCommand("Comprar Medicina");
        btnMedicina.setBorderPainted(false);
        btnMedicina.setContentAreaFilled(false);
        btnMedicina.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicina.png"))); // NOI18N
        btnMedicina.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/medicina 3.png"))); // NOI18N
        add(btnMedicina, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 730, 110, 110));

        btnPastilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastilla.png"))); // NOI18N
        btnPastilla.setActionCommand("Comprar Pastilla");
        btnPastilla.setBorderPainted(false);
        btnPastilla.setContentAreaFilled(false);
        btnPastilla.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastilla.png"))); // NOI18N
        btnPastilla.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastilla 3.png"))); // NOI18N
        add(btnPastilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 730, 110, 110));

        leche.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        leche.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(leche, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 540, 60, 30));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel7.setText("Leche:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 550, -1, -1));

        agua.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        agua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 500, 60, 30));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel8.setText("Agua:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 510, -1, -1));

        pollo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pollo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(pollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 540, 60, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel5.setText("Pollo:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 550, -1, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel11.setText("Medicina:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 860, -1, -1));

        pescado.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        pescado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(pescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 60, 30));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel6.setText("Pescado:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel4.setText("Carne:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 510, -1, -1));

        carne.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        carne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(carne, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 500, 60, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 11)); // NOI18N
        jLabel3.setText("Cerdo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, -1, -1));

        btnCLeche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leche 2.png"))); // NOI18N
        btnCLeche.setActionCommand("Comprar Leche");
        btnCLeche.setBorderPainted(false);
        btnCLeche.setContentAreaFilled(false);
        btnCLeche.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leche 2.png"))); // NOI18N
        btnCLeche.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/leche 3.png"))); // NOI18N
        add(btnCLeche, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 350, 110, 110));

        btnCPollo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pollo 2.png"))); // NOI18N
        btnCPollo.setActionCommand("Comprar Pollo");
        btnCPollo.setBorderPainted(false);
        btnCPollo.setContentAreaFilled(false);
        btnCPollo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pollo 2.png"))); // NOI18N
        btnCPollo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pollo 3.png"))); // NOI18N
        add(btnCPollo, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 350, 110, 110));

        btnCPescado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pescado 2.png"))); // NOI18N
        btnCPescado.setActionCommand("Comprar Pescado");
        btnCPescado.setBorderPainted(false);
        btnCPescado.setContentAreaFilled(false);
        btnCPescado.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pescado 2.png"))); // NOI18N
        btnCPescado.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pescado 3.png"))); // NOI18N
        add(btnCPescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 350, 110, 110));

        btnCAgua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agua 2.png"))); // NOI18N
        btnCAgua.setActionCommand("Comprar Agua");
        btnCAgua.setBorderPainted(false);
        btnCAgua.setContentAreaFilled(false);
        btnCAgua.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agua 2.png"))); // NOI18N
        btnCAgua.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agua 3.png"))); // NOI18N
        add(btnCAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, 110, 110));

        btnCCarne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carne 2.png"))); // NOI18N
        btnCCarne.setActionCommand("Comprar Carne");
        btnCCarne.setBorderPainted(false);
        btnCCarne.setContentAreaFilled(false);
        btnCCarne.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carne 2.png"))); // NOI18N
        btnCCarne.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carne 3.png"))); // NOI18N
        add(btnCCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 230, 110, 110));

        btnCCerdo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerdo 2.png"))); // NOI18N
        btnCCerdo.setActionCommand("Comprar Cerdo");
        btnCCerdo.setBorderPainted(false);
        btnCCerdo.setContentAreaFilled(false);
        btnCCerdo.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerdo 2.png"))); // NOI18N
        btnCCerdo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerdo 3.png"))); // NOI18N
        add(btnCCerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 230, 110, 110));

        cerdo.setFont(new java.awt.Font("Rockwell", 1, 12)); // NOI18N
        cerdo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(cerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 500, 60, 30));

        dinero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(dinero, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, 40, 20));

        jLabel2.setText("Dinero:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, -1, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/tienda.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agua;
    private javax.swing.JButton btnCAgua;
    private javax.swing.JButton btnCCarne;
    private javax.swing.JButton btnCCerdo;
    private javax.swing.JButton btnCLeche;
    private javax.swing.JButton btnCPescado;
    private javax.swing.JButton btnCPollo;
    private javax.swing.JButton btnJabon;
    private javax.swing.JButton btnMedicina;
    private javax.swing.JButton btnPastilla;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel carne;
    private javax.swing.JLabel cerdo;
    private javax.swing.JLabel dinero;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jabon;
    private javax.swing.JLabel leche;
    private javax.swing.JLabel medicina;
    private javax.swing.JLabel pastilla;
    private javax.swing.JLabel pescado;
    private javax.swing.JLabel pollo;
    // End of variables declaration//GEN-END:variables
}
