/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.vista;

import javax.swing.table.DefaultTableModel;
import ucr.ac.cr.controlador.ControladorA;
import ucr.ac.cr.controlador.ControladorG;
import ucr.ac.cr.modelo.Jugador;
import ucr.ac.cr.modelo.Partida;

/**
 *
 * @author Mónica Artavia
 */
public class PanelReporte extends javax.swing.JPanel {

    private ControladorA controladorA;
    private ControladorG controladorG;
    /**
     * Creates new form PanelReporte
     */
    public PanelReporte() {
        initComponents();
    }
    
    public void escuchar(ControladorA controladorA){
        btnOk.addActionListener(controladorA);
    }
    
    public void escucharG(ControladorG controladorG){
        btnOk.addActionListener(controladorG);
    }
    
    public void mostrarOk(boolean estado){
        btnOk.setVisible(estado);
    }
    
    public void setDatosTablaJ(String [][] datos){
        tbReporteJ.setModel(new DefaultTableModel(datos, Jugador.ETIQUETAS_JUGADOR));
        jScrollPane2.setViewportView(tbReporteJ);
    }
    
    public void setDatosTablaP(String [][] datos){
        tbReporteP.setModel(new DefaultTableModel(datos, Partida.ETIQUETAS_PARTIDA));
        jScrollPane1.setViewportView(tbReporteP);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbReporteP = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbReporteJ = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOk.setText("Ok");
        add(btnOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 60, 30));

        tbReporteP.setBackground(new java.awt.Color(255, 204, 255));
        tbReporteP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nivel", "Salud"
            }
        ));
        tbReporteP.setGridColor(new java.awt.Color(0, 0, 0));
        tbReporteP.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane1.setViewportView(tbReporteP);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 260, 50));

        tbReporteJ.setBackground(new java.awt.Color(255, 204, 255));
        tbReporteJ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre de usuario", "Nombre del felino"
            }
        ));
        tbReporteJ.setGridColor(new java.awt.Color(0, 0, 0));
        tbReporteJ.setSelectionBackground(new java.awt.Color(204, 255, 255));
        jScrollPane2.setViewportView(tbReporteJ);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CREDITOS.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-100, 100, -1, 130));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbReporteJ;
    private javax.swing.JTable tbReporteP;
    // End of variables declaration//GEN-END:variables
}
