/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.vista;


import ucr.ac.cr.controlador.ControladorInicio;


/**
 *
 * @author Mónica Artavia
 */
public class PanelRegistro extends javax.swing.JPanel {

    private ControladorInicio controlador;
    /**
     * Creates new form PanelRegistro
     */
    public PanelRegistro() {
        initComponents();
    }
    
    public void escuchar(ControladorInicio controlador){
        btnAmarillo.addActionListener(controlador);
        btnGris.addActionListener(controlador);
        btnCrear.addActionListener(controlador);
        btnCancelar.addActionListener(controlador);
    }
    
    public void amarillo(){
        amarillo.setVisible(true);
        amarilloNo.setVisible(false);
        grisNo.setVisible(true);
        gris.setVisible(false);
    }
    
    public void gris(){
        gris.setVisible(true);
        grisNo.setVisible(false);
        amarilloNo.setVisible(true);
        amarillo.setVisible(false);
    }
    
    public void mostrarElegido(String titulo){
        lblPersonaje.setText(titulo);
    }
    
    public void limpiar(){
        lblPersonaje.setText("Personaje");
        txtNombreJ.setText("");
        txtNombreP.setText("");
    }

    public void setLblPersonaje(String lblTxtPersonaje) {
        this.lblPersonaje.setText(lblTxtPersonaje);
    }

    public String getLblTxtPersonaje() {
        return lblPersonaje.getText().trim();
    }

    public String getTxtNombreP() {
        return txtNombreP.getText().trim();
    }

    public void setTxtNombreP(String txtNombreP) {
        this.txtNombreP.setText(txtNombreP);
    }

    public String getTxtNombreJ() {
        return txtNombreJ.getText().trim();
    }

    public void setTxtNombreJ(String txtNombreJ) {
        this.txtNombreJ.setText(txtNombreJ);
    }
    
    public void mostrarCancelado(){
        btnCancelar.setVisible(true);
        btnAmarillo.setVisible(false);
        btnGris.setVisible(false);
        btnCrear.setVisible(false);
        txtNombreJ.setVisible(false);
        txtNombreP.setVisible(false);
        gris.setVisible(false);
        grisNo.setVisible(false);
        amarilloNo.setVisible(false);
        amarillo.setVisible(false);
        lblPersonaje.setVisible(false);
        lblNombre.setVisible(false);
        lblNombre1.setVisible(false);
    }
    
    public void ocultarCancelado(){
        btnCancelar.setVisible(false);
        btnAmarillo.setVisible(true);
        btnGris.setVisible(true);
        btnCrear.setVisible(true);
        txtNombreJ.setVisible(true);
        txtNombreP.setVisible(true);
        gris.setVisible(false);
        grisNo.setVisible(true);
        amarilloNo.setVisible(true);
        amarillo.setVisible(false);
        lblPersonaje.setVisible(true);
        lblNombre.setVisible(true);
        lblNombre1.setVisible(true);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNombreJ = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        lblPersonaje = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        grisNo = new javax.swing.JLabel();
        gris = new javax.swing.JLabel();
        amarilloNo = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        btnAmarillo = new javax.swing.JButton();
        btnGris = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CREAR.png"))); // NOI18N
        btnCrear.setActionCommand("Crear");
        btnCrear.setBorderPainted(false);
        btnCrear.setContentAreaFilled(false);
        btnCrear.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CREAR.png"))); // NOI18N
        btnCrear.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CR.png"))); // NOI18N
        add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 740, 180, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/REINICIAR.png"))); // NOI18N
        btnCancelar.setActionCommand("Reiniciar Registro");
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/img/REINICIAR.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RR.png"))); // NOI18N
        add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 560, 200, -1));

        txtNombreJ.setBackground(new java.awt.Color(255, 204, 255));
        txtNombreJ.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreJ.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreJ.setOpaque(false);
        add(txtNombreJ, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 130, 240, 30));

        lblNombre1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lblNombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre1.setText("ESCRIBE TU NOMBRE");
        add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 90, 340, 40));

        lblPersonaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonaje.setText("Personaje");
        add(lblPersonaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 670, 120, 50));

        txtNombreP.setBackground(new java.awt.Color(255, 204, 255));
        txtNombreP.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreP.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtNombreP.setOpaque(false);
        add(txtNombreP, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 230, 240, 30));

        lblNombre.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        lblNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombre.setText("ESCRIBE EL NOMBRE DE TU FELINO");
        add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 340, 40));

        grisNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gris registro.png"))); // NOI18N
        add(grisNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 310, 320, 480));

        gris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Gris normal volteado.png"))); // NOI18N
        add(gris, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 310, 320, 480));

        amarilloNo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Amarillo registro.png"))); // NOI18N
        add(amarilloNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 309, 320, 480));

        amarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Amarillo normal.png"))); // NOI18N
        add(amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 309, 320, 480));

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/registro.png"))); // NOI18N
        add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnAmarillo.setText("Amarillo");
        add(btnAmarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 300, 420));

        btnGris.setText("Gris");
        add(btnGris, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 300, 420));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amarillo;
    private javax.swing.JLabel amarilloNo;
    private javax.swing.JButton btnAmarillo;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnGris;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel gris;
    private javax.swing.JLabel grisNo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPersonaje;
    private javax.swing.JTextField txtNombreJ;
    private javax.swing.JTextField txtNombreP;
    // End of variables declaration//GEN-END:variables
}
